# Generated by Django 3.0.2 on 2020-01-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('postingID', models.AutoField(primary_key=True, serialize=False)),
                ('classCode', models.CharField(max_length=15, verbose_name='Class Code')),
                ('className', models.CharField(max_length=80, verbose_name='Class Name')),
                ('classDesc', models.TextField(verbose_name='Class Description')),
                ('semester', models.CharField(max_length=50, verbose_name='Semester')),
                ('position', models.CharField(max_length=25, verbose_name='Position')),
                ('school', models.CharField(max_length=80, verbose_name='School')),
                ('percentTime', models.IntegerField(blank=True, null=True, verbose_name='Percent Time')),
                ('hoursPerWk', models.IntegerField(verbose_name='Hours Per Week')),
                ('feeRemission', models.BooleanField(default=True, verbose_name='Fee Remission')),
                ('instructor', models.CharField(max_length=200, verbose_name='Instructor')),
                ('mode', models.CharField(max_length=80, verbose_name='Mode')),
                ('instructorBio', models.URLField(verbose_name='Instructor Bio')),
                ('classDays', models.CharField(max_length=20, verbose_name='Class Days')),
                ('classStartTime', models.CharField(max_length=15, verbose_name='Class Start Time')),
                ('classEndTime', models.CharField(max_length=15, verbose_name='Class End Time')),
                ('numPositions', models.IntegerField(blank=True, null=True, verbose_name='Number of Positions')),
                ('positionNotes', models.TextField(blank=True, verbose_name='Notes')),
                ('appDueDate', models.TextField(verbose_name='App Due Date')),
                ('appURL', models.URLField(verbose_name='App URL')),
            ],
        ),
    ]
