# Generated by Django 3.0.2 on 2020-01-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ase_site', '0002_auto_20200113_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='classDays',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Class Days'),
        ),
    ]
