# Generated by Django 3.0.2 on 2020-01-13 07:02

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ase_site', '0003_auto_20200113_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='appURL',
        ),
        migrations.AddField(
            model_name='posting',
            name='content_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='posting',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content_search'], name='ase_site_po_content_2c0a43_gin'),
        ),
    ]
