# Generated by Django 3.0.2 on 2020-01-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ase_site', '0004_auto_20200113_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='appURL',
            field=models.URLField(null=True, verbose_name='App URL'),
        ),
    ]
