# Generated by Django 3.0.2 on 2020-01-13 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ase_site', '0005_posting_appurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='appDueDate',
            new_name='app_due_date',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='appURL',
            new_name='app_url',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='classCode',
            new_name='class_code',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='classDays',
            new_name='class_days',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='classDesc',
            new_name='class_desc',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='classEndTime',
            new_name='class_end_time',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='className',
            new_name='class_name',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='classStartTime',
            new_name='class_start_time',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='feeRemission',
            new_name='fee_remission',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='hoursPerWk',
            new_name='hours_per_wk',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='instructorBio',
            new_name='instructor_bio',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='numPositions',
            new_name='num_positions',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='percentTime',
            new_name='percent_time',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='positionNotes',
            new_name='position_notes',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='postingID',
            new_name='posting_id',
        ),
    ]
