# Generated by Django 3.0.2 on 2020-01-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ase_site', '0006_auto_20200113_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='position',
            field=models.CharField(choices=[('gsi', 'GSI'), ('head_gsi', 'Head GSI'), ('gsr', 'GSR'), ('tutor', 'Tutor'), ('reader', 'Reader'), ('course_asst', 'Course Assistant')], max_length=25, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='school',
            field=models.CharField(choices=[('information', 'Information'), ('economics', 'Economics'), ('cog_sci', 'Cognitive Science')], max_length=80, verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='semester',
            field=models.CharField(choices=[('fall_2019', 'Fall 2019'), ('spring 2020', 'Spring 2020')], max_length=50, verbose_name='Semester'),
        ),
    ]
