# Generated by Django 3.0.2 on 2020-01-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ase_site', '0007_auto_20200113_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='semester',
            field=models.CharField(blank=True, choices=[('fall_2019', 'Fall 2019'), ('spring 2020', 'Spring 2020')], max_length=50, verbose_name='Semester'),
        ),
    ]
