# Generated by Django 3.0.2 on 2020-01-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ase_site', '0008_auto_20200113_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='position',
            field=models.CharField(choices=[('GSI', 'GSI'), ('Head GSI', 'Head GSI'), ('GSR', 'GSR'), ('Tutor', 'Tutor'), ('Reader', 'Reader'), ('Course Asst', 'Course Assistant')], max_length=25, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='school',
            field=models.CharField(choices=[('Information', 'Information'), ('Economics', 'Economics'), ('Cognitive Science', 'Cognitive Science')], max_length=80, verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='semester',
            field=models.CharField(blank=True, choices=[('Fall 2019', 'Fall 2019'), ('Spring 2020', 'Spring 2020')], max_length=50, verbose_name='Semester'),
        ),
    ]
