# Generated by Django 3.0.2 on 2020-01-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ase_site', '0009_auto_20200113_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='position',
            field=models.CharField(blank=True, choices=[('GSI', 'GSI'), ('Head GSI', 'Head GSI'), ('GSR', 'GSR'), ('Tutor', 'Tutor'), ('Reader', 'Reader'), ('Course Asst', 'Course Assistant')], max_length=25, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='school',
            field=models.CharField(blank=True, choices=[('Information', 'Information'), ('Economics', 'Economics'), ('Cognitive Science', 'Cognitive Science')], max_length=80, verbose_name='School'),
        ),
    ]
