# Generated by Django 3.0.2 on 2020-01-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ase_site', '0010_auto_20200113_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='percent_time',
            field=models.IntegerField(blank=True, choices=[('25%', '25%'), ('50%', '50%'), ('75%', '75%')], null=True, verbose_name='Percent Time'),
        ),
    ]
