# Generated by Django 3.0.2 on 2020-01-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ase_site', '0011_auto_20200113_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='percent_time',
            field=models.IntegerField(blank=True, choices=[('15%', '15%'), ('25%', '25%'), ('40%', '40%'), ('50%', '50%'), ('75%', '75%')], max_length=4, null=True, verbose_name='Percent Time'),
        ),
    ]
