# Generated by Django 3.0.2 on 2020-01-13 23:29

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ase_site', '0013_auto_20200113_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='content_search',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
